var indexData = [
"@;0:1",
"ability;1:1",
"abomination;1:2",
"abroad;1:3",
"absorb the small states into the empire;1:4",
"abyss of despair;1:5",
"accessories, fittings;1:6",
"accomplish extraordinary works;1:7",
"account, value, estimate, give reckoning;1:8",
"accuse, to appeal to higher court;1:9",
"acquainted with each other;1:10",
"act of faith;1:11",
"active, brisk, vigorous, person very active and lively;1:12",
"adapted to present conditions;1:13",
"addresss by an honorable designation, to address style, designation;1:14",
"administer poison secretly;1:15",
"admittance;1:16",
"advance to higher school;1:17",
"advise others not to do evil;1:18",
"affidavit, statements or transcript made in the courts;1:19",
"after school, after school hours, terminate class, release from school, return home from school at the end of the day's classes;1:20",
"age of puberty;1:21",
"agony, agonize, be in anguish, in great pain, pain of dying, distress, depression;1:22",
"aide-de-camp;1:23",
"aisle;1:24",
"alive and active;1:25",
"all the evils, extremely evil;1:26",
"allow me to pass or get by you, please.;1:27",
"already too late;1:28",
"always smiling, all smiles;1:29",
"amethyst;1:30",
"amputation;1:31",
"ancient and modern;1:32",
"angry and unpleasant sound or tone of voice, as at the beginning of quarrel;1:33",
"announce or set forth one's political views;1:34",
"another one, distinct from the one named;1:35",
"anti-communism;1:36",
"anxious grieved state of mind;1:37",
"apoplectic fit;1:38",
"appearance of face or person, facial features, prime minister, pictures;1:39",
"appoint a day;1:40",
"approach a person, bring about better relationships;1:41",
"arbitrate;1:42",
"argue with me, dispute with me;1:43",
"army commander;1:44",
"arrangement committee;1:45",
"article made to order, custom made article;1:46",
"as regards the spirit;1:47",
"ask for;1:48",
"aspiration, short prayer;1:49",
"assist soul to get deliverance from punishment and be born into this world again;1:50",
"astound;1:51",
"at the point of death;1:52",
"attach oneself to a place;1:53",
"attentively;1:54",
"august;1:55",
"autocracy;1:56",
"avert, prevent, avoid, forestall, to prevent something from happening, dodge, evade, get away;1:57",
"axis;1:58",
"azalea;1:59",
"backward children;2:1",
"bail out, release on bail;2:2",
"bamboo conduit for water used in country places;2:3",
"bank, bank up a river, snow or fire;2:4",
"bar, horizontal beam atop door frame, sliding wooden lock of big doors, prison bars;2:5",
"bartender;2:6",
"bathtub;2:7",
"beam, timber;2:8",
"beat person black and blue;2:9",
"become buddha;2:10",
"bedstead;2:11",
"beggar ware, free software;2:12",
"behind, at the back of;2:13",
"belong;2:14",
"benevolence;2:15",
"betel nut peddler;2:16",
"bible class;2:17",
"bill of exchange, cashier's check, personal check, share, stock, equity;2:18",
"bird, to peck like a bird, to earn,make a profit, cheat, swindle;2:19",
"black and withered as leaves or decaying fruit, black and blue as when beaten;2:20",
"blaze;2:21",
"bloated;2:22",
"blot, stain, smear, flaw, defect, blemish;2:23",
"boast of or display one's own skill, ability;2:24",
"boiled very soft, overdone, wrapped or sealed and cooked till soft or mushy;2:25",
"book or books in general, lists, statistical tables;2:26",
"borrow or get something from many sources;2:27",
"bound volume;2:28",
"boycott;2:29",
"brandish;2:30",
"break off by twisting;2:31",
"breast cancer;2:32",
"bride's father-in-law;2:33",
"bring forth;2:34",
"brochure, admissions guide listing essential points for entrance to school;2:35",
"brother-in-law;2:36",
"buddha's gilded image;2:37",
"building expenses, the cost of construction;2:38",
"bureau of mines;2:39",
"bury corpse;2:40",
"busy;2:41",
"buyer bargaining for better price;2:42",
"byzantine;2:43",
"calamity;3:1",
"call to mind, think, remember;3:2",
"can hold or maintain frontline, position, chastity, regulation;3:3",
"canned food, tinned meats or fruit;3:4",
"cannot get through with my meaning, he is impenetrable: he won't listen;3:5",
"canticle;3:6",
"captain of a team;3:7",
"cardboard box;3:8",
"cargo on a boat or plane;3:9",
"carry passengers;3:10",
"cassiflowers, osmanthus flowers;3:11",
"catch sight of, see;3:12",
"cause obstruction or impediment, involve;3:13",
"celebrated, famous;3:14",
"centigrade;3:15",
"ceremony of offering presents;3:16",
"chairs and tables, furniture;3:17",
"change one's plans, language, manner to suit new circumstances;3:18",
"character, written character;3:19",
"charm, amulet;3:20",
"cheated and suffer loss;3:21",
"cherish an evil intention;3:22",
"chief of police;3:23",
"children's songs;3:24",
"chisel;3:25",
"christ;3:26",
"cinnamon;3:27",
"citizen's identification card, id card;3:28",
"clairvoyance;3:29",
"classical language;3:30",
"clear off debts;3:31",
"cliff;3:32",
"close down shop, go bankrupt or insolvent;3:33",
"clothes rack;3:34",
"coarse wooden comb;3:35",
"coffee machine, coke machine, soft drinks machine;3:36",
"cold-hearted;3:37",
"college of commerce;3:38",
"comatose;3:39",
"come to conclusion, concluding passage or movement, settle an affair, put things in order, clear away;3:40",
"commandment;3:41",
"commission somebody;3:42",
"common, held collectively;3:43",
"commuter's ticket;3:44",
"compelled to do something;3:45",
"complete corpse;3:46",
"compliment, greeting, praise, congratulations;3:47",
"compulsory education;3:48",
"concentric, of one heart;3:49",
"concurrence;3:50",
"conference;3:51",
"confirm a rumor;3:52",
"confused, to tangled, disheveled;3:53",
"conjugal harmony;3:54",
"consciously, knowingly;3:55",
"considerate, thoughtful, attentive;3:56",
"constantly, very frequently;3:57",
"consumers;3:58",
"contention;3:59",
"contraceptives, the pill;3:60",
"control;3:61",
"converted;3:62",
"cool, good, great;3:63",
"copy, record, make an entry, take notes, consign;3:64",
"corpse, carcass;3:65",
"corrupt, be corrupted, to ruin, be ruined;3:66",
"council;3:67",
"countless aspects or forms of world and natural phenomena;3:68",
"court-martial;3:69",
"cover up warmly so as to perspire;3:70",
"crafty and injurious;3:71",
"credit, credit installments;3:72",
"criminal psychology;3:73",
"crops lacking rain;3:74",
"crowded, congested;3:75",
"crushed flat with the hand;3:76",
"cuff, sleeves;3:77",
"cure tea, tobacco leaves;3:78",
"curse or scolding meaning stupid ignorant person;3:79",
"customs dues, tax;3:80",
"cutting edge of knife;3:81",
"czechoslovakia;3:82",
"dance, dancing;4:1",
"dark, black color of chicken's skin;4:2",
"day;4:3",
"dead or alive;4:4",
"death;4:5",
"decay;4:6",
"decidedly;4:7",
"decrease, diminution, fall off;4:8",
"deep sea;4:9",
"defend, vindicate;4:10",
"defraud on taxes;4:11",
"deliberately;4:12",
"delivery service;4:13",
"demonstrate how a thing works, show one's skill;4:14",
"department;4:15",
"deplore, complain, sorrow, sad;4:16",
"deputed, order of appointment in written form;4:17",
"desiccated or dried meat;4:18",
"despise people;4:19",
"detain;4:20",
"develop, body development, body building;4:21",
"diabetes;4:22",
"didactic;4:23",
"difference, distinction, distinguish;4:24",
"digestive, a medicinal aid to digestion;4:25",
"dimple;4:26",
"direct or supervise the manufacture of;4:27",
"dirty, filthy, to defile;4:28",
"discern between good and bad;4:29",
"discontented with one's position;4:30",
"disdain, dislike;4:31",
"disheveled, hair all mussed up and dirty;4:32",
"disobedient son;4:33",
"dispense with formalities;4:34",
"dispute;4:35",
"dissolute;4:36",
"distinguished service;4:37",
"disuse;4:38",
"divine pill, elixir, panacea;4:39",
"do it by yourself.;4:40",
"do, manage;4:41",
"doesn窶冲 want to offend people;4:42",
"dominant;4:43",
"dope, drugs;4:44",
"down;4:45",
"drag, pull;4:46",
"draw lots to determine the prize winners in a raffle or lottery;4:47",
"dress, a dress;4:48",
"drink;4:49",
"dropouts, dropout student;4:50",
"dual nationality;4:51",
"dump one's work or responsibility off on another person;4:52",
"dutiable;4:53",
"dysphemia, stammer, stutter, someone who stammers or stutters;4:54",
"earn, make money, to gain;5:1",
"easily tired;5:2",
"eat meat and fish;5:3",
"eco-friendly;5:4",
"edification;5:5",
"effect, influence;5:6",
"egoist;5:7",
"elder female fellow student under the same master or tutor;5:8",
"electric rice cooker, hot pot or pan;5:9",
"electrotherapy;5:10",
"eliminate unnecessary staff or personnel, lay off workers;5:11",
"embark, set out on a journey, begin some venture;5:12",
"emery cloth;5:13",
"employee;5:14",
"enclose minced stuffing;5:15",
"end, cut short, break off, become extinct;5:16",
"energy crisis;5:17",
"engross;5:18",
"enmity, hostility, antagonism;5:19",
"enter into partnership;5:20",
"entrance, enter into;5:21",
"epaulets;5:22",
"equall size;5:23",
"erasmus;5:24",
"escape from prison;5:25",
"essential points, the important points;5:26",
"eternal life;5:27",
"evade trouble;5:28",
"eventually;5:29",
"evict, recover;5:30",
"exactly next door;5:31",
"examine oneself;5:32",
"excellent, lofty and intelligent, one who has attained high position;5:33",
"excited;5:34",
"execute criminals, execution, torture prisoner;5:35",
"exhaust fan above gas stove or range;5:36",
"exonerate;5:37",
"expel the breath, breathe heavily, to blow or puff open;5:38",
"expiate;5:39",
"export, foreign sales;5:40",
"exquisite, intense, refined;5:41",
"extinguish a fire, put out a fire, beat out a fire;5:42",
"extravagant person;5:43",
"eyeball;5:44",
"ezra;5:45",
"facility, fluent, fluency;6:1",
"fail, failure, defeat;6:2",
"faithfully serve god;6:3",
"fallout, atomic fallout;6:4",
"family education;6:5",
"far east;6:6",
"fast;6:7",
"father and mother, parents;6:8",
"favorable;6:9",
"feather duster;6:10",
"feel heavy in the stomach;6:11",
"fellow countrymen overseas, overseas chinese;6:12",
"ferment, brew, brewing;6:13",
"feverfew, febrifuge, white chrysanthemum;6:14",
"fifteen percent discount;6:15",
"file, folder, for holding papers or records;6:16",
"final end;6:17",
"fine arts;6:18",
"fire blazes up or kindles;6:19",
"first and second epistle of paul to the corinthians;6:20",
"first step, elementary steps, a primer;6:21",
"fishing with line and hook;6:22",
"fixed date, appointed day, term, time limit;6:23",
"flat feet;6:24",
"flex;6:25",
"flood waters overflowed the levee;6:26",
"flower show;6:27",
"flytrap;6:28",
"follow people but lose track of them, miss an appointment to go somewhere;6:29",
"food parcels packaged ready to eat;6:30",
"footpad;6:31",
"force;6:32",
"foreign exchange, certificates;6:33",
"forge metal, to temper, to train, to discipline;6:34",
"form, compose, constitute, organize;6:35",
"formerly, long ago;6:36",
"forty;6:37",
"fount of life;6:38",
"fragrance, aroma, sweet smell, perfume;6:39",
"free movement, a free hand, free action;6:40",
"frequently, often, usually;6:41",
"friendship;6:42",
"from poverty become rich, from rags to riches;6:43",
"fruit;6:44",
"fulfill one's mission;6:45",
"function;6:46",
"furnace or incinerator for burning gold paper near the pagodas;6:47",
"fx, movie special effects;6:48",
"gambling;7:1",
"garnish;7:2",
"gaul;7:3",
"general name for a melon or gourd;7:4",
"genetic health law, abortion law;7:5",
"germ, sprout;7:6",
"get or take something by posing as someone else for whom it is intended;7:7",
"ghosts and spirits, demons and gods;7:8",
"gist of an event, the real story, unapparent details of a matter;7:9",
"give a pay raise, a pay-hike;7:10",
"gladiator;7:11",
"gloria, the lesser doxology;7:12",
"go along a road, pass by;7:13",
"go out, be out of town, absent from home or office;7:14",
"godfather;7:15",
"good, good things;7:16",
"good name that will last forever;7:17",
"goodwill between china and america;7:18",
"government and the people;7:19",
"gradient, grade, inclination;7:20",
"grandiloquent, boastful;7:21",
"grate vegetables;7:22",
"great bear, the big dipper, north star;7:23",
"greek;7:24",
"grim;7:25",
"grounds, basis, reason, proof;7:26",
"grumble, complain, ventilate one's emotions;7:27",
"guest or visitors;7:28",
"gunfire;7:29",
"gypsy;7:30",
"hale, vigorous;8:1",
"hand, human hand;8:2",
"handle of a drawer;8:3",
"hanker after or dote upon wealth or improper things;8:4",
"hard on the ears;8:5",
"harm;8:6",
"hat worn by officials;8:7",
"have as an attachd institution;8:8",
"have male offspring;8:9",
"have painful sores, severe boils, abscesses;8:10",
"have twins;8:11",
"head of the military instructors in a school;8:12",
"hear incorrectly, misunderstand what one has heard said;8:13",
"heartless, fickle, ungrateful, destitute of good feelings, grown cold in friendship;8:14",
"heavy, serious, grave;8:15",
"help stand up;8:16",
"herd;8:17",
"hew with a sword;8:18",
"high speed railway;8:19",
"hike in prices;8:20",
"historical;8:21",
"hobbyhorse, trojan horse, paper dolls ;8:22",
"hold a post for another term, eligible for re-election;8:23",
"hollow affection;8:24",
"home visits;8:25",
"honolulu;8:26",
"hope for, long for, to wish, expect eagerly;8:27",
"hospital;8:28",
"hour, sixty minutes, time;8:29",
"how can this be right? how absurd!;8:30",
"human power, strength, efforts;8:31",
"hunger, hungry, famine, scarcity ;8:32",
"husk, turn a hand-mill, grind into flour;8:33",
"hypnotic, hypnotic medicines, sleeping pill;8:34",
"hysterics;8:35",
"ideogram;9:1",
"ignorance, ignorant;9:2",
"illuminate all things, shed light on;9:3",
"imitate a man;9:4",
"imminent danger;9:5",
"impassable;9:6",
"imperial throne;9:7",
"import duty;9:8",
"impound, forfeiture, custody, detention, detained, put in cage;9:9",
"improve one's destiny;9:10",
"in delicate health, frail health, have a weak constitution;9:11",
"in the army, in the armed forces;9:12",
"inadvertently;9:13",
"incense, fragrant powder or stick;9:14",
"inclose 100 dollars in a letter;9:15",
"inconsiderate child;9:16",
"increasingly;9:17",
"indelible impression;9:18",
"indifferent attitude;9:19",
"indoor;9:20",
"ineffaceable;9:21",
"infant prodigy;9:22",
"infinite or perfect good;9:23",
"influence reproduction and development;9:24",
"ingenious things, rare articles;9:25",
"inject medicine;9:26",
"inmate;9:27",
"inquiry office;9:28",
"inside the mouth;9:29",
"inspector, surveyor;9:30",
"instituted or founded by the country, national;9:31",
"insuperable;9:32",
"intense, highly emotional;9:33",
"interdict;9:34",
"intermediary in business;9:35",
"internment camp;9:36",
"intervene in, meddle, interpose;9:37",
"intrigue, tactics, schemes;9:38",
"inverse proportion;9:39",
"invincible might;9:40",
"inwardly;9:41",
"irregularity;9:42",
"islamism;9:43",
"iwo jima;9:44",
"jasper, emerald;10:1",
"jig, dance;10:2",
"joint communique;10:3",
"jubilation, joy;10:4",
"jumble up, be mixed together, be commingled, be mingled with;10:5",
"jurymen;10:6",
"juxtaposition;10:7",
"keep the commandments;11:1",
"kidnap for ransom, person held for ransom by brigands, seize for ransom;11:2",
"kind and hospitable;11:3",
"kit;11:4",
"knives and swords;11:5",
"know the difference between good and evil;11:6",
"kyoto;11:7",
"lack sleep;12:1",
"lama;12:2",
"land to the tiller, final phase of the land reform program on taiwan;12:3",
"larceny;12:4",
"last agony;12:5",
"latter;12:6",
"law case, circumstances of a judicial case, details of a case;12:7",
"lay hold of;12:8",
"leaden, heavy;12:9",
"leap up and down frantically;12:10",
"leave off drinking;12:11",
"leek stalks, leek stems;12:12",
"legendary life;12:13",
"lent;12:14",
"lethargy;12:15",
"liaison office, station;12:16",
"lie face downward;12:17",
"lifeline in figurative sense;12:18",
"lightly;12:19",
"limited liability company;12:20",
"lining;12:21",
"listen, but could not understand;12:22",
"little extra piece of work which can be done conveniently;12:23",
"live together, cohabit;12:24",
"loathsome;12:25",
"lodging;12:26",
"long soft cucumber, much used as a vegetable, a dishcloth gourd;12:27",
"look down upon others;12:28",
"loop, contraceptive device, an iud;12:29",
"lose in debate;12:30",
"lost sheep;12:31",
"love of country, patriotism;12:32",
"lower part;12:33",
"lucky moment and lucky day, auspicious day;12:34",
"lustful;12:35",
"lysol;12:36",
"magic lantern;13:1",
"mail, a letter sent in the mail;13:2",
"maintenance;13:3",
"make an indentation with the thumbnail, to press with fingernails;13:4",
"make a good guess, guess right or cor- rectly, expect beforehand;13:5",
"make others unhappy;13:6",
"make the matter widely known through the press, clarify or announce by a news- paper advertisement;13:7",
"malaria;13:8",
"malleable iron;13:9",
"man of poor judgment;13:10",
"mandatory powers;13:11",
"man's disposition, his moral or intellectual standing, character of a person, personality;13:12",
"many, numerous, all, multitude, the masses, public or popular opinion, views;13:13",
"mark time;13:14",
"married daughter returning to the home of her parents and picking up things to take back to the home of her husband;13:15",
"mashed garlic, garlic pounded soft;13:16",
"master key;13:17",
"material, substances;13:18",
"matter, affair;13:19",
"may you have good fortune according to your desires;13:20",
"meaning;13:21",
"meat stall;13:22",
"medical course;13:23",
"mediterranean sea;13:24",
"meeting place, conference hall;13:25",
"members of a family;13:26",
"menology, biography of distinguished ladies;13:27",
"mercilessly deserted his wife and children;13:28",
"messy hair;13:29",
"meticulous, cautious, with meticulous care;13:30",
"middle-aged chicken, not yet fully grown;13:31",
"military achievements, martial arts;13:32",
"military telephone;13:33",
"mind or heart is in confusion and anxious;13:34",
"minister of finance;13:35",
"mire;13:36",
"misfortune, grave danger, help in crisis;13:37",
"missy, a young girl;13:38",
"mixed blood, child of an inter-racial marriage, half-breed, child of mixed ancestry;13:39",
"moderator, mediator;13:40",
"molecular formula;13:41",
"money given as gift for new year;13:42",
"mononucleosis;13:43",
"monthly ticket;13:44",
"morality;13:45",
"morning prayers;13:46",
"most beautiful;13:47",
"motion pictures depicting the chivalry and prowess of ancient swordsmen;13:48",
"mounting, to climb, to pull oneself up;13:49",
"move a corpse to the funeral parlor;13:50",
"mower;13:51",
"mule;13:52",
"murmur at one's fate;13:53",
"must, mould;13:54",
"muzzle, the circumference of one's mouth;13:55",
"mythology;13:56",
"narrate;14:1",
"national education, compulsory education;14:2",
"native to the place, local person;14:3",
"nature, character, disposition, temperament, temper;14:4",
"nearby, neighboring, vicinity;14:5",
"negation, decide against, vote down;14:6",
"nerve cells;14:7",
"never seen before;14:8",
"news of illicit love;14:9",
"nick, in the nick of time, come in the nick of time;14:10",
"nirvana, as a human aim;14:11",
"no room to place or store anything;14:12",
"nominal company;14:13",
"noose;14:14",
"not able to fully hear or understand what was said;14:15",
"not know which side to turn to, be indecisive, be in a dilemma;14:16",
"not to know, not to acknowledge, not to understand, not acquainted with;14:17",
"nothing;14:18",
"novitiate;14:19",
"number, serial number;14:20",
"nut, difficult problem;14:21",
"nylon;14:22",
"objector;15:1",
"observance, to comply with, to abide by;15:2",
"obstruct traffic;15:3",
"occupy an important position in the ministry of education;15:4",
"ode;15:5",
"off, at a distance, remote, take a vacation, separate, freetime;15:6",
"offer tribute, pay tribute that a vassal owes to his suzerain;15:7",
"officer in charge of the regiment, regimental commander, company commander;15:8",
"oh! why does it hurt so much?;15:9",
"old things;15:10",
"on guard against an incident, etc, guard against;15:11",
"once or twice;15:12",
"one thing;15:13",
"one's mother country;15:14",
"online banking;15:15",
"open out like a dress, door or window;15:16",
"operate a lathe;15:17",
"oppose, disobey;15:18",
"optional subject;15:19",
"order, arrange, arrangement, put in order;15:20",
"ordinary member of a society;15:21",
"origin, beginning, genesis;15:22",
"osb: benedictine srs;15:23",
"our side;15:24",
"outhouse, out door privy;15:25",
"outside the door;15:26",
"over there, the other, the other party, the other side;15:27",
"overjoyed;15:28",
"overthrown, to overturn a regime by plotting or subversion, to undermine;15:29",
"ownership, title to property;15:30",
"ozone layer;15:31",
"pageant, pageantry;16:1",
"pal, familiar person;16:2",
"pancreas;16:3",
"paper fastener;16:4",
"parallel, to compare;16:5",
"parentage, lineage, origin, descent;16:6",
"parsimony, stingy, mean, miserly;16:7",
"participation, taking part in;16:8",
"party, political party;16:9",
"pass, succeed, do something successfully, to go smoothly, to come off;16:10",
"password, word of command, watchword;16:11",
"patch, mend clothes;16:12",
"patient must be isolated.;16:13",
"paul;16:14",
"pay or handover benefits;16:15",
"peaceful, at ease;16:16",
"pedagogue;16:17",
"pekingese dog, pug;16:18",
"penetrated with hatred;16:19",
"people, the common people;16:20",
"percent, ...out of 100;16:21",
"perfectly;16:22",
"perfunctory;16:23",
"perishable, dies easily;16:24",
"perplex, cause complications;16:25",
"person from the same home district, fellow citizen of the same district;16:26",
"personal stereo;16:27",
"perverse and tyrannical ruler;16:28",
"petrochemical industry;16:29",
"philanthropic acts, auspicious matters like births and marriage;16:30",
"photograph;16:31",
"physiognomist;16:32",
"pickle vegetables;16:33",
"piece of meat;16:34",
"pilgrim;16:35",
"pink;16:36",
"pitfall;16:37",
"place, land, location;16:38",
"plan, scheme;16:39",
"plaque, memorial;16:40",
"play doubles in tennis, doubles;16:41",
"plead ignorance;16:42",
"plenteous, rich, abundant, vast, great, ample, affluent;16:43",
"plumage;16:44",
"point, to point out;16:45",
"poke into;16:46",
"policy of government meets hopes of people.;16:47",
"politics, political strategy;16:48",
"pool in a stream, a small lake or pond;16:49",
"popular, pertaining to the common people;16:50",
"porter's lodge;16:51",
"positivism;16:52",
"postal parcel;16:53",
"potatoes;16:54",
"poverty;16:55",
"powerful countries;16:56",
"pragmatism;16:57",
"precarious, uncertain, exposed to risk;16:58",
"preclude;16:59",
"prefect of studies;16:60",
"prelude, omen, prognosis in medicine;16:61",
"prepare a feast;16:62",
"present a gift;16:63",
"preside over one's destiny;16:64",
"pressure cooker;16:65",
"pretended sympathy and grief;16:66",
"previous remarks, words of past thinkers, a foreword, a preface;16:67",
"primacy;16:68",
"principal person concerned in any matter, client, victim in a criminal case;16:69",
"prison, jail, behind bars;16:70",
"probiotic;16:71",
"proclaim, certify, give witness to;16:72",
"product;16:73",
"profitable work, investment;16:74",
"prohibition of sales;16:75",
"promise verbally, to grant;16:76",
"pronounce, emit sound, articulate, enunciate;16:77",
"proper way or course;16:78",
"propose, to suggest, to initiate, proposal, initiative, recommendations;16:79",
"prostitution and gambling;16:80",
"protuberant, jutting, convex, protrude;16:81",
"provincialism, narrow minded loyalty to one's hometown;16:82",
"psalm;16:83",
"public expenditure, government funds;16:84",
"publication, notice, announcement;16:85",
"pull outside;16:86",
"punish an offender lightly;16:87",
"purgatory;16:88",
"pus;16:89",
"put a mark on;16:90",
"putrefy, rot;16:91",
"pyx;16:92",
"quantitative;17:1",
"queen of peace;17:2",
"quick to awake, be watchful and careful of one's conduct;17:3",
"quite, completely, entirely;17:4",
"quote, quote a price for something;17:5",
"radical change, fundamentally changed;18:1",
"ragged clothes;18:2",
"raise domestic animals, livestock industry;18:3",
"ramshackle, tottering, on the verge of collapse;18:4",
"rarely;18:5",
"rattan chair, cane chair;18:6",
"reaction force;18:7",
"ready, ready-made, at hand;18:8",
"reappoint, renew, continue to employ a person;18:9",
"rebellious army, rebels, rebellious troops;18:10",
"receive guests, entertain guests;18:11",
"reception room, anteroom;18:12",
"recline or lean on a couch or chair, lean against, push a boat along with a pole;18:13",
"record or copy names;18:14",
"rector of a church;18:15",
"redound;18:16",
"reference to someone or something;18:17",
"refractory child;18:18",
"refuse, lees, dregs, sediment in liquor, grains in distilled liquor;18:19",
"region, district, zone, area;18:20",
"regular, usual;18:21",
"reject impure thoughts;18:22",
"relax one's attention, to ease, loosen;18:23",
"relieve oneself of responsibility, spread infectious diseases;18:24",
"rely on father's wealth;18:25",
"remember;18:26",
"remove or change one's census registration;18:27",
"renounce one's will;18:28",
"repeat prayers, chant liturgies;18:29",
"report for duty, report one's arrival;18:30",
"reproach;18:31",
"repute, to believe, to think, to consider, to feel;18:32",
"resemblance;18:33",
"resign en masse, usually a cabinet;18:34",
"resource, method, means, strategy, tactics;18:35",
"responsibility;18:36",
"restore order by effort;18:37",
"resume, summary, abstract;18:38",
"retrace one's steps;18:39",
"return to one's native place;18:40",
"reverential;18:41",
"revoke a permit or license;18:42",
"rhythm, safe period;18:43",
"riches and honor;18:44",
"right hand, right-hand side;18:45",
"ring the phone, call somebody;18:46",
"risk, danger, to take risks;18:47",
"roast tea leaves;18:48",
"roll call book, attendance record book;18:49",
"room, rooms built below the ground, cellar, underground vault, basement;18:50",
"rough cloth or hands;18:51",
"rowboat;18:52",
"rudimentary;18:53",
"run a shop;18:54",
"running around in circles, frantically busy;18:55",
"ryukyu islands;18:56",
"sacrilegious;19:1",
"sail the seas, maritime navigation;19:2",
"salted or pickled meat, fish or shellfish sliced in small pieces;19:3",
"sample goods, specimen;19:4",
"sarcastic laugh;19:5",
"saucer, small plate;19:6",
"say hello, greet somebody, use one's influence on another's behalf, warn;19:7",
"scan;19:8",
"scene, landscape, vista;19:9",
"school established by the city, municipal schools;19:10",
"scold somebody indirectly, scold, abuse person by ostensibly pointing to someone else;19:11",
"scrap, a small piece;19:12",
"scripture;19:13",
"sea waves;19:14",
"seat, chair, bench;19:15",
"secondhand clothes;19:16",
"secrets of an art, a key to;19:17",
"sediment or dregs in water;19:18",
"seek employment, look for a job;19:19",
"seize, occupy, confiscate;19:20",
"self respect, prudence, be deliberate in;19:21",
"sells, sales, marketing;19:22",
"send a letter to a newspaper editor, contribute articles to, an anonymous notice;19:23",
"sense organs;19:24",
"separated by distance, far away from, depart for a distant place;19:25",
"serum, watery matter from a wound, soft slimy dirt, the slime on an eel or fish's skin;19:26",
"set in order, arrange, enumerate, rank, classify, series, row, line;19:27",
"settled, resolved, account settled;19:28",
"severely wounded;19:29",
"shady and pleasantly cool;19:30",
"shape;19:31",
"shave the beard;19:32",
"shelter thieves;19:33",
"shipwreck, sunken ship, scuttle a ship;19:34",
"shoplifter;19:35",
"shorten;19:36",
"show a good example;19:37",
"shrimp;19:38",
"sickly;19:39",
"sight testing chart;19:40",
"silicone implant;19:41",
"simple food, ordinary meal, potluck, everyday fare;19:42",
"sinews and bones;19:43",
"sinicized, influenced by the chinese milieu;19:44",
"sit and crouch down warming self by a fire;19:45",
"six lower intestines: gall blatter, stomach, large and small bowels and the urinary organs;19:46",
"skilled workman;19:47",
"sky is getting dark;19:48",
"sleep, slumber;19:49",
"slightly;19:50",
"sloven;19:51",
"small door;19:52",
"smart, intelligent;19:53",
"smokestack;19:54",
"snappy;19:55",
"snuff tobacco;19:56",
"soccer, soccer football;19:57",
"sock, socks;19:58",
"solder, soldering tin;19:59",
"solitary, alone, lonely, friendless;19:60",
"something that very rarely happens, blooming of an iron tree, an impossibility;19:61",
"soot, black irritating smoke;19:62",
"soul, spirit, mind;19:63",
"source;19:64",
"spa, bath therapy, hydrotherapy;19:65",
"sparkling;19:66",
"speak with authority;19:67",
"specialist, expert, professional;19:68",
"speech;19:69",
"sperm whale;19:70",
"spirit, vigor, vitality, drive, spiritual, soul;19:71",
"spit out phlegm;19:72",
"sponge;19:73",
"spray, small branch, twig;19:74",
"sprinkle, splash;19:75",
"squat, podgy;19:76",
"staff, flag staff;19:77",
"stall or booth especially a fixed one in a market;19:78",
"standard pronunciation;19:79",
"starling bird;19:80",
"state clearly, make a statement;19:81",
"station, position, status, place in society;19:82",
"steal;19:83",
"stem, to stop, to prohibit, plug up;19:84",
"stern family discipline;19:85",
"stiff collar;19:86",
"stinky;19:87",
"stomach area;19:88",
"stop the water supply, turn off the water supply;19:89",
"storm signal;19:90",
"straightforward, clear-cut, blunt statement, simply;19:91",
"stratagem;19:92",
"strength, ability;19:93",
"strike head, bump or ram the head;19:94",
"strive together, common endeavor, joint effort;19:95",
"structure, construction, organization;19:96",
"study abroad using personal funds;19:97",
"stunted or scraggy like an ill-formed tree, bare rocky hill;19:98",
"subdue the concupiscences;19:99",
"subordinate;19:100",
"subterfuge;19:101",
"successive;19:102",
"sue, take to court, litigate, plead, have a lawsuit;19:103",
"suffrage, voting rights;19:104",
"sulfate, sulphate;19:105",
"sun;19:106",
"superficial faith;19:107",
"superstition;19:108",
"support, back up, patronage;19:109",
"surely sealed;19:110",
"surrogate mother;19:111",
"suspense, concerned;19:112",
"swear to fight to finish;19:113",
"sweltering;19:114",
"swollen lymphatic gland;19:115",
"synagogue;19:116",
"szechwan style cuisine;19:117",
"tackle, equipment;20:1",
"taiwan, penghu, kinmen and matsu;20:2",
"take care of one's reputation, have a sense of honor;20:3",
"take somebody's fancy, to win approval;20:4",
"talent, tact, capacity, ability;20:5",
"tame, boring, plain;20:6",
"tapping or knocking sound;20:7",
"tasteful, discerning;20:8",
"tea kettle;20:9",
"tear body limb from limb, drawn and quartered;20:10",
"teetotum with six sides, dice;20:11",
"tell the truth, to speak truthfully;20:12",
"temporality, property rights;20:13",
"tenant, guest at a hotel;20:14",
"tense atmosphere;20:15",
"terminate, limited, restrict to;20:16",
"terrorism;20:17",
"textile factory;20:18",
"theatrical;20:19",
"there;20:20",
"thieves' den;20:21",
"thinking people, feeling people;20:22",
"this, root, foundation, basis;20:23",
"thrash, rummage;20:24",
"threshold, doorstep, doorsill;20:25",
"throw a ball;20:26",
"thunderstruck, killed or injured by lightening strike;20:27",
"tie a knot;20:28",
"timber;20:29",
"timpani;20:30",
"title;20:31",
"toddle;20:32",
"tomfoolery, act like a clown;20:33",
"too much for one to finish or accomplish;20:34",
"torch bearers, candle bearers;20:35",
"total, grand total;20:36",
"tow, pull or drag;20:37",
"traction, to drag, to pull, to trail, to delay, to haul;20:38",
"trail, footprint, mark, trace, vestige, sign, indication;20:39",
"tranquil, quiet, peaceful, calm;20:40",
"transfer, change, turn, exchange;20:41",
"translucent, semitransparent;20:42",
"transverse;20:43",
"treacherous smile;20:44",
"treatment, hospitality, welcome;20:45",
"trial, experiment with;20:46",
"trigonometry;20:47",
"troop, a bunch, a group;20:48",
"trowel, small shovel;20:49",
"trust in god;20:50",
"try to say it;20:51",
"tumult, to disturb, to perturb, to harass;20:52",
"turn off the light;20:53",
"turquoise;20:54",
"twinkling stars;20:55",
"typist;20:56",
"tyro, new hand, novice, raw recruit;20:57",
"unable to be seated;21:1",
"unanimous;21:2",
"unburden one's heart of a secret;21:3",
"uncommon qualities;21:4",
"under the hand, under the power or control of, underling, subordinate;21:5",
"undersecretary;21:6",
"undisciplined mob;21:7",
"unexpected accident;21:8",
"unfurnished room;21:9",
"union;21:10",
"universally known, known by all;21:11",
"unmarried, single;21:12",
"unprecedented achievement;21:13",
"unrest;21:14",
"unsuccessful;21:15",
"unwilling to do, do reluctantly;21:16",
"upkeep;21:17",
"upstart, nouveau riche;21:18",
"usb, universal serial bus;21:19",
"usher in the new and send off the old;21:20",
"utterly conscienceless;21:21",
"uxoricide;21:22",
"valid period;22:1",
"vanity of the world;22:2",
"vast sum of money;22:3",
"vein;22:4",
"ventricle of the heart;22:5",
"verse, stanza;22:6",
"vestige, remains, trace;22:7",
"vicinity;22:8",
"vigorous, active, lively, spirited, vigorous;22:9",
"violent typhoon;22:10",
"virus, pathogens;22:11",
"visual, sight, vision;22:12",
"vocational;22:13",
"volume, bulk;22:14",
"vulgar in manner, very cheap and inferior;22:15",
"vulva;22:16",
"wake up, awake, conscious;23:1",
"wallow, addicted to or absorbed in wine and women;23:2",
"wanton, given to lust, lecherous, lascivious, horny;23:3",
"warm;23:4",
"wash clean;23:5",
"watch of the night, one fifth part of the night;23:6",
"water is rising;23:7",
"way, road, path;23:8",
"wealth, money;23:9",
"weave, fabricate;23:10",
"weigh one's words;23:11",
"well water;23:12",
"western style toilet bowl, commode;23:13",
"what place?;23:14",
"whenever he has some money, he goes to drink.;23:15",
"while, time, when, hour, season, period;23:16",
"white grape wine;23:17",
"whole village;23:18",
"wide band;23:19",
"wild cat, harlot, vile scolding;23:20",
"willing to endure;23:21",
"wind, breath;23:22",
"winter bamboo shoots;23:23",
"wit, quick-witted, tact, witty, resourceful;23:24",
"withered;23:25",
"withstand, resist, resistance;23:26",
"womanizing, gambling and drunkenness;23:27",
"wood vessels, furniture;23:28",
"words;23:29",
"workers' health insurance;23:30",
"worldly desires;23:31",
"worst;23:32",
"wrap up;23:33",
"write down or record one's name;23:34",
"written prayer;23:35",
"www, world wide web;23:36",
"xylophone, marimba;24:1",
"yearning, to thirst for, to long for;25:1",
"young and old;25:2",
"youngsters and young adults;25:3",
"yule tide;25:4",
"zoroastrianism;26:1",
];
